---
title: "Recent Talks"
date: last-modified
callout-appearance: simple
title-block-banner: false
# https://www.anl.gov/sites/www/files/2021-09/CPA_RESIZE_Climate%20Resilience%20Images_01_1920x1080.jpg
editor:
   render-on-save: true
execute:
   freeze: true
---

<!-- ::: {.callout-tip icon="false" title="" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}: -->
<!-- <iframe loading="lazy" allow="picture-in-picture" src="" title="🪧 L" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> -->
<!--   <p>Your browser does not support iframes.</p> -->
<!-- </iframe> -->
<!-- ::: -->

## 📆 2024



::: {.callout-tip icon="false" title="🪧 [[**Parallel Training Techniques**](https://github.com/saforem2/parallel-training-slides) @ [_AI-4-Science Training Series_](https://github.com/argonne-lcf/ai-science-training-series/tree/main/06_parallel_training) \[03/2024\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/parallel-training-slides" title="🪧 Parallel Training Techniques" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
  <p>Your browser does not support iframes.</p>
</iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**LLMs from Scratch**](https://github.com/saforem2/llm-workshop-talk) @ [_LLM Tutorial Workshop (2)_](https://github.com/argonne-lcf/llm-workshop) \[02/2024\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-workshop-talk" title="🪧 LLMs from Scratch" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
  <p>Your browser does not support iframes.</p>
</iframe>

:::

## 📆 2023

::: {.callout-tip icon="false" title="🪧 [[**Creating Small(-ish) LLMs**](https://github.com/saforem2/LLM-tutorial) @ [_LLM Tutorial Workshop (1)_](https://github.com/brettin/llm_tutorial) \[11/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/LLM-tutorial" title="🪧 Creating Small(-ish) LLMs" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
  <p>Your browser does not support iframes.</p>
</iframe>

:::

<!-- ::: {.callout-tip icon="false" title="🪧 [[**LLM Lunch Talk**](https://github.com/saforem2/llm-lunch-talk)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}: -->
<!---->
<!-- <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-lunch-talk" title="🪧 LLMs on Polaris" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> -->
<!--   <p>Your browser does not support iframes.</p> -->
<!-- </iframe> -->
<!---->
<!-- ::: -->

::: {.callout-tip icon="false" title="🪧 [[**Exascale Science on Aurora**](https://saforem2.github.io/oneapi-talk) @ [_Intel oneAPI Workshop @ UIC_](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/oneapi-talk/#0"  title="🪧 Exascale Science on Aurora" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**LLM Lunch Talk**](https://saforem2.github.io/llm-lunch-talk) @ [_ALCF Hands On HPC Workshop_](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-lunch-talk/#/section" title="🪧 LLMs on Polaris" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Scaling LLMs for Science and Ongoing Collaborations**](https://saforem2.github.io/scaling4science) @ [_Data-Intensive Computing and AI/ML at Scale_](https://events.cels.anl.gov/event/426/overview) \[08/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/scaling4science/#/section" title="🪧 Scaling LLMs for Science and Ongoing Collaborations" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**MLMC: Machine Learning Monte Carlo**](https://saforem2.github.io/lattice23) @ [_Lattice 2023_](https://indico.fnal.gov/event/57249/contributions/271305/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/lattice23/#/title-slide" title="🪧 MLMC: Machine Learning Monte Carlo" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Generative Modeling and Efficient Sampling**](https://saforem2.github.io/lqcd-pasc23/) @ [_PASC23_](https://pasc23.pasc-conference.org/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/lqcd-pasc23/" title="🪧 Generative Modeling and Efficient Sampling" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Efficient Sampling for Lattice Gauge Theory**](https://saforem2.github.io/deep-fridays) @ [_Deep Fridays @ U. Bologna_](https://www.cs.unibo.it/~asperti/deep_fridays.html) \[04/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/deep-fridays/" title="🪧 Efficient Sampling for Lattice Gauge Theory" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::


## 📆 2022

::: {.callout-tip icon="false" title="🪧 [[**Large Scale Training**](https://saforem2.github.io/ai4sci-large-scale-training) @ [_Introduction to AI4Science on Supercomputers (ALCF)_](https://github.com/argonne-lcf/ai-science-training-series) \[11/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/ai4sci-large-scale-training/#" title="🪧 Large Scale Training" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Hyperparameter Management**](https://saforem2.github.io/hparam-management-sdl2022/) @ [_ALCF Simulation, Data, and Learning Workshop_](https://www.alcf.anl.gov/events/2022-alcf-simulation-data-and-learning-workshop) \[10/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/hparam-management-sdl2022" title="🪧 Hyperparameter Management" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Statistical Learning**](https://saforem2.github.io/ATPESC-StatisticalLearning) @ [_ATPESC 2022_](https://extremecomputingtraining.anl.gov/) \[08/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

- [📕 accompanying notebook](https://github.com/argonne-lcf/ATPESC_MachineLearning/blob/master/00_statisticalLearning/src/atpesc/notebooks/statistical_learning.ipynb)

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/ATPESC-StatisticalLearning/#/" title="🪧 Statistical Learning" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Scientific Data Science: An Emerging Symbiosis**](https://saforem2.github.io/anl-job-talk/) @ ANL \[05/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/anl-job-talk" title="🪧 Scientific Data Science" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip icon="false" title="🪧 [[**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar) @ UNC Greensboro \[03/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

- [**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar), at UNC Greensboro, March 2022  

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/physicsSeminar" title="🪧 Machine Learning in HEP" width="100%" align="center" height="300" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

## 📆 2021

::: {.callout-tip icon="false" title="🪧 [[**Accelerated Sampling Methods for Lattice Gauge Theory**](https://saforem2.github.io/l2hmc-dwq25/), @ [_BNL / DWQ @ 25_](https://indico.bnl.gov/event/13576/) \[12/2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/l2hmc-dwq25/" title="🪧 Accelerated Sampling Methods for Lattice Gauge Theory" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::


::: {.callout-tip icon="false" title="🪧 [[**Training Topological Samplers for Lattice Gauge Theory**](https://saforem2.github.io/l2hmc_talk_ect2021) @ [_ML4HEP, ECT\* Trento_](https://indico.ectstar.eu/event/77/contributions/2349/) \[09/2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}

  <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/l2hmc_talk_ect2021" title="🪧 Training Topological Samplers for Lattice Gauge Theory" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::


::: {.callout-tip icon="false" title="🪧 [[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) @ MIT Lattice Group Seminar \[2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:


[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) at the *MIT Lattice Group Seminar*, 2021

:::


::: {.callout-tip icon="false" title="🪧 [[**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) @ [_ML in LQCD Workshop_](https://bit.ly/mainz21_overview) \[2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:

<!-- -   [**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) to the [*Machine Learning Techniques in Lattice QCD Workshop*](https://bit.ly/mainz21_overview), 2021 -->

<iframe loading="lazy" allow="picture-in-picture" src="https://bit.ly/mainz21" title="🪧 Deep Learning HMC for Improved Gauge Generation" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

## 📆 2020

::: {.callout-tip icon="false" title="🪧 [[**Machine Learning for Lattice QCD**](https://slides.com/samforeman/l2hmc-qcd-93bc0c) @ U. Iowa (2020)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-color: var(--bg-border)!important;"}:

<iframe loading="lazy" allow="picture-in-picture" src="https://slides.com/samforeman/l2hmc-qcd-93bc0c" title="🪧 Machine Learning for Lattice QCD" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::
