## 📆 2025

::: {.callout-tip icon=false title="[[**Scientific AI at Scale: AI for Science**](/talks/openskai25/ai4science/index.html) @ [Open SkAI 2025](https://www.openskai-conference.org) \[09/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="https://samforeman.me/talks/openskai25/ai4science/slides#" title="AuroraGPT: Large Scale Training on Diverse Accelerators" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**Scientific AI at Scale: Distributed Training**](/talks/openskai25/training/index.html) @ [Open SkAI 2025](https://www.openskai-conference.org/) \[09/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="https://samforeman.me/talks/openskai25/training/slides.html" title="Scientific AI at Scale: Distributed Training" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**AuroraGPT: Large Scale Training on Diverse Accelerators**](/talks/AuroraGPT-SIAM25/index.html) @ [Scalable Deep Learning,  *SIAM AN2025*](https://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=84772) \[07/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="https://samforeman.me/talks/AuroraGPT-SIAM25/slides#" title="AuroraGPT: Large Scale Training on Diverse Accelerators" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**LLMs on Aurora: 🌌 AuroraGPT**](/talks/incite-hackathon-2025/AuroraGPT/index.html) @ [_2025 ALCF INCITE GPU Hackathon_](https://www.alcf.anl.gov/events/alcf-incite-gpu-hackathon) \[05/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

- [🎥 video](https://www.youtube.com/watch?v=KJBbR_oFO2E)

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="https://samforeman.me/talks/incite-hackathon-2025/AuroraGPT/slides#/section" title="LLMs on Aurora: AuroraGPT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

<!-- ::: {.callout-tip icon=false title="[[**🍋 <code>ezpz</code> on Aurora**](/talks/incite-hackathon-2025/ezpz/index.html) @ [_2025 ALCF INCITE GPU Hackathon_](https://www.alcf.anl.gov/events/alcf-incite-gpu-hackathon) \[05/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "} -->
::: {.callout-tip icon=false title="[[**LLMs on Aurora: 🍋 ezpz**](/talks/incite-hackathon-2025/ezpz/index.html) @ [_2025 ALCF INCITE GPU Hackathon_](https://www.alcf.anl.gov/events/alcf-incite-gpu-hackathon) \[05/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

- [🎥 video](https://www.youtube.com/watch?v=15ZK9REQiBo)

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="https://samforeman.me/talks/incite-hackathon-2025/ezpz/slides#/section" title="🍋 ezpz on Aurora" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**AuroraGPT: Foundation Models for Science**](/talks/aurora-gpt-fm-for-electric-grid/index.html) @ [_Foundation Models for the Electric Grid_](https://www.alcf.anl.gov/alcf-ai-science-training-series) \[02/2025\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}
::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="/talks/aurora-gpt-fm-for-electric-grid/slides.html" title="AuroraGPT: Foundation Models for Science" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

## 📆 2024

::: {.callout-tip icon=false title="[[**Parallel Training Methods**](/talks/ai-for-science-2024/index.html) @ [_AI-for-Science on Supercomputers_](https://www.alcf.anl.gov/alcf-ai-science-training-series) \[11/2024\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

- [🎥 video](https://www.youtube.com/watch?v=4ltulBj4oVk)

::: {.reveal-full-page}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="/talks/ai-for-science-2024/slides.html" title="Parallel Training Methods" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**AuroraGPT**](/talks/AuroraGPT/alcf-hpc-workshop-2024/index.html) @ [_2024 ALCF Hands-On HPC Workshop_](https://www.alcf.anl.gov/events/2024-alcf-hands-hpc-workshop)  \[10/2024\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}

- [🎥 video](https://www.youtube.com/watch?v=15ZK9REQiBo)

::: {.reveal-full-page}
<iframe class="slide-deck" loading="lazy" src="/talks/AuroraGPT/alcf-hpc-workshop-2024/slides.html" title="AuroraGPT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**Machine Learning and Foundation Models at Scale**](/talks/alcf-hpc-workshop-2024/index.html) @ [_2024 ALCF Hands-On HPC Workshop_](https://www.alcf.anl.gov/events/2024-alcf-hands-hpc-workshop)  \[10/2024\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}
::: {.reveal-full-page}
<iframe class="slide-deck" loading="lazy" src="https://samforeman.me/talks/alcf-hpc-workshop-2024/slides#/section" title="Machine Learning and Foundation Models at Scale" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon=false title="[[**AuroraGPT**](/talks/hpc-user-forum/index.html) @ [_HPC User Forum_, 2024](https://www.hpcuserforum.com/hpc-user-forum-fall-2024/) \[09/2024\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}
<iframe class="slide-deck reveal-full-page" loading="lazy" src="/talks/hpc-user-forum/slides.html" title="AuroraGPT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::

::: {.callout-tip icon=false title="[[**Training LLMs at Scale**](/talks/llms-at-scale/) @ [_ATPESC_, 2024](https://extremecomputingtraining.anl.gov/atpesc-2024/) \[08/2024\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important; "}
<iframe class="slide-deck" loading="lazy" src="/talks/llms-at-scale/slides.html" title="Training LLMs at Scale" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::

::: {.callout-tip icon=false title="[[**LLMs on Polaris**](https://samforeman.me/talks/llms-on-polaris/slides) @ [_Center for Scientific Foundation Models_, Summer School 24'](https://scifm.ai/summer_school.html) \[07/2024\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
<iframe class="slide-deck" loading="lazy" src="/talks/llms-on-polaris/slides.html" title="LLMs on Polaris" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::

::: {.callout-tip icon=false title="[[**Parallel Training Techniques**](https://github.com/saforem2/parallel-training-slides) @ [_AI-4-Science Training Series_](https://github.com/argonne-lcf/ai-science-training-series/tree/main/06_parallel_training) \[03/2024\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/parallel-training-slides" title="Parallel Training Techniques" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip title="[[**LLMs from Scratch**](https://saforem2.github.io/llm-workshop-talk) @ [LLM Tutorial Workshop](https://github.com/argonne-lcf/llm-workshop) \[02/2024\]]{.dim-text}" icon="false" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}:
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/llm-workshop-talk" title="LLMs from Scratch" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

## 📆 2023

::: {.callout-tip icon="false" title="[[**Creating Small(-ish) LLMs**](https://saforem2.github.io/LLM-tutorial) @ [LLM Tutorial Workshop (1)](https://github.com/brettin/llm_tutorial) \[11/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}:
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/LLM-tutorial" title="Creating Small(-ish) LLMs" align="center" frameborder="0" webkitallowfullscreen allowfullscreen > </iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Exascale Science on Aurora**](https://saforem2.github.io/oneapi-talk) @ [Intel oneAPI Workshop @ UIC](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/oneapi-talk" title="Exascale Science on Aurora" align="center" frameborder="0" webkitallowfullscreen allowfullscreen > </iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**LLM Lunch Talk**](https://saforem2.github.io/llm-lunch-talk) @ [ALCF Hands On HPC Workshop](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}

- [🎥 video](https://www.youtube.com/watch?v=mSx9RVd00xU)

::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/llm-lunch-talk/#/section" title="LLMs on Polaris" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Scaling LLMs for Science**](https://saforem2.github.io/scaling4science) @ [Data-Intensive Computing + AI/ML at Scale](https://events.cels.anl.gov/event/426/overview) \[08/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/scaling4science/#/section" title="Scaling LLMs for Science and Ongoing Collaborations" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**MLMC: Machine Learning Monte Carlo**](https://saforem2.github.io/lattice23) @ [Lattice 2023](https://indico.fnal.gov/event/57249/contributions/271305/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/lattice23/#/title-slide" title="MLMC: Machine Learning Monte Carlo" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Generative Modeling and Efficient Sampling**](https://saforem2.github.io/lqcd-pasc23/) @ [PASC23](https://pasc23.pasc-conference.org/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/lqcd-pasc23/" title="Generative Modeling and Efficient Sampling" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Efficient Sampling for LGT**](https://saforem2.github.io/deep-fridays) @ [Deep Fridays @ U. Bologna](https://www.cs.unibo.it/~asperti/deep_fridays.html) \[04/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/deep-fridays/" title="Efficient Sampling for LGT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

## 📆 2022

::: {.callout-tip icon="false" title="[[**Large Scale Training**](https://saforem2.github.io/ai4sci-large-scale-training) @ [AI4Science on Supercomputers (ALCF)](https://github.com/argonne-lcf/ai-science-training-series) \[11/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/ai4sci-large-scale-training/#" title="Large Scale Training" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Hyperparameter Management**](https://saforem2.github.io/hparam-management-sdl2022/) @ [ALCF SDL Workshop](https://www.alcf.anl.gov/events/2022-alcf-simulation-data-and-learning-workshop) \[10/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/hparam-management-sdl2022" title="Hyperparameter Management" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Statistical Learning**](https://saforem2.github.io/ATPESC-StatisticalLearning) @ [ATPESC 2022](https://extremecomputingtraining.anl.gov/) \[08/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
- [📕 accompanying notebook](https://github.com/argonne-lcf/ATPESC_MachineLearning/blob/master/00_statisticalLearning/src/atpesc/notebooks/statistical_learning.ipynb)


::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/ATPESC-StatisticalLearning/#/" title="Statistical Learning" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::

:::

::: {.callout-tip icon="false" title="[[**Scientific Data Science: An Emerging Symbiosis**](https://saforem2.github.io/anl-job-talk/) @ ANL (05/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/anl-job-talk" title="Scientific Data Science" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar) @ UNC Greensboro \[03/2022\]]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(0,0,0,0.0)!important;"}
- [**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar), at UNC Greensboro, March 2022  

::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/physicsSeminar" title="Machine Learning in HEP" align="center" frameborder="0" webkitallowfullscreen allowfullscreen style="width:100%!important; "></iframe>
:::

:::

## 📆 2021

::: {.callout-tip icon="false" title="[[**Accelerated Sampling Methods for LGT**](https://saforem2.github.io/l2hmc-dwq25/), @ [DWQ @ 25 \[BNL\]](https://indico.bnl.gov/event/13576/) \[12/2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/l2hmc-dwq25/" title="Accelerated Sampling Methods for LGT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**Training Topological Samplers for LGT**](https://saforem2.github.io/l2hmc_talk_ect2021) @ [ML4HEP, ECT\* Trento](https://indico.ectstar.eu/event/77/contributions/2349/) \[09/2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://saforem2.github.io/l2hmc_talk_ect2021" title="Training Topological Samplers for LGT" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::

::: {.callout-tip icon="false" title="[[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) @ MIT Lattice Group Seminar \[2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}:
[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) at the _MIT Lattice Group Seminar_, 2021
:::

::: {.callout-tip icon="false" title="[[**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) @ [ML in LQCD Workshop](https://bit.ly/mainz21_overview) \[2021\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}:
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://slides.com/samforeman/dlhmc/embed" title="Deep Learning HMC for Improved Gauge Generation" scrolling="no" frameborder="0" webkitallowfullscreen allowfullscreen style="aspect-ratio:1.3671875;"></iframe>
:::
:::

## 📆 2020

::: {.callout-tip icon="false" title="[[**Machine Learning for Lattice QCD**](https://slides.com/samforeman/l2hmc-qcd/embed) @ U. Iowa \[2020\]]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(0,0,0,0.0)!important;"}:
::: {.embedded-slide}
<iframe class="slide-deck" loading="lazy" src="https://slides.com/samforeman/l2hmc-qcd/embed" title="Machine Learning for Lattice QCD" align="center" frameborder="0" webkitallowfullscreen allowfullscreen  style="aspect-ratio:1.3671875;"></iframe>
:::
:::
