- [HiPerRAG: High-Performance Retrieval Augmented Generation for Scientific Insights](https://arxiv.org/abs/2505.04846)  
  [O. Gokdemir et al., _05/2025_]{.dim-text}

- [MOFA: Discovering Materials for Carbon Capture with a GenAI and Simulation-Based Workflow](https://arxiv.org/abs/2501.10651)  
  [Xiaoli Yan et al., _01/2025_]{.dim-text}

- [**MProt-DPO: Breaking the ExaFLOPS Barrier for Multimodal Protein Design Workflows with Direct Preference Optimization**](https://doi.org/10.1109/SC41406.2024.00013)
  [G. Dharuman, K. Hippe, A. Brace, **S. Foreman**, et al. @ [SC'24](https://sc24.supercomputing.org/)]{.dim-text}

  - {{< iconify noto-v1 bell>}} [[2024 ACM Gordon Bell Finalist]{.highlight-pink}](https://sc24.supercomputing.org/2024/10/presenting-the-finalists-for-the-2024-gordon-bell-prize/)

- [Intro to HPC Bootcamp: Engaging New Communities Through Energy Justice Projects](https://jocse.org/downloads/jocse-15-1-10.pdf)  
    [Journal of Computational Science, _2024_]{.dim-text}

- [Thorough Characterization and Analysis of Large Transformer Model Training At-Scale](https://doi.org/10.1145/3639034)  
    [Proc. ACM Meas. Anal. Comput. Syst. _03/2024_]{.dim-text}

- [MLMC: Machine Learning Monte Carlo for Lattice Gauge Theory](https://arxiv.org/abs/2312.08936)  
    [**S. Foreman** et al. [Lattice, 2023 (Proceedings)](https://indico.fnal.gov/event/57249/), _12/2023_]{.dim-text}

- [Protein Generation via Genome-scale Language Models with Bio-physical Scoring ](https://dl.acm.org/doi/abs/10.1145/3624062.3626087)  
    [@ SC'23, _11/2023_]{.dim-text}

- {{< iconify logos microsoft-icon >}} [**DeepSpeed4Science Initiative**: Enabling Large-Scale Scientific Discovery \[...\]](https://arxiv.org/abs/2310.04610)  
    [@ [NeurIPS 2023 AI For Science Workshop](https://ai4sciencecommunity.github.io/neurips23.html), _10/2023_]{.dim-text}

  - [{{< iconify fluent-emoji-flat test-tube >}} DeepSpeed4Science.ai Blog Post](https://deepspeed4science.ai/2023/09/18/model-showcase-genslms/)

  - [{{< iconify fluent-emoji-flat newspaper >}} Loooooooong Sequence Lengths](/posts/AuroraGPT/long-sequences/index.qmd)

- [Comprehensive Performance Study of LLMs on Novel AI Accelerators](https://arxiv.org/abs/2310.04607)  
    [M. Emani, **S. Foreman**, et al., [IPDPS 2024](https://www.ipdps.org/), _10/2023_]{.dim-text}

- [Exploratory Analysis of Climate Data with `ClimRR`](https://saforem2.github.io/climate-analysis)  
    [**S. Foreman**, [Intro to HPC Bootcamp @ NERSC](https://github.com/NERSC/intro-HPC-bootcamp-2023), _08/2023_]{.dim-text}

- {{< iconify noto-v1 trophy >}} [**GenSLMs: Genome-scale language models reveal SARS-Cov-2 evolutionary dynamics**](https://www.biorxiv.org/content/10.1101/2022.10.10.511571v1.abstract)  
    [@ SC'22 _10/2022_]{.dim-text}

  - 🥇 [[ACM Gordon Bell Special Prize]{.highlight-pink}](https://www.acm.org/media-center/2023/november/gordon-bell-special-prize-covid-research-2022)

- [Lattice QCD and Particle Physics](https://arxiv.org/abs/2207.07641)  
    [A.S. Kronfeld et al., _07/2022_]{.dim-text}

- [Applications of ML to Lattice QFT](https://arxiv.org/abs/2202.05838)  
    [D. Boyda, S. Calí, **S. Foreman**, et al., \[[_arXiv:2202.05838_](https://arxiv.org/abs/2202.05838)\], _02/2022_]{.dim-text}

- [LeapFrogLayers: Trainable Framework for Effective Sampling](https://arxiv.org/abs/2112.01582)  
    [**S. Foreman**, X.Y. Jin, J.C. Osborn, [Lattice, _2021_](https://indico.cern.ch/event/1006302)]{.dim-text}

- [HMC with Normalizing Flows](https://arxiv.org/abs/2112.01586) \[[slides](https://indico.cern.ch/event/1006302/contributions/4380743/)\]  
    [**S. Foreman** et al., [Lattice, _2021_](https://indico.cern.ch/event/1006302/)]{.dim-text}

- [Deep Learning Hamiltonian Monte Carlo](https://arxiv.org/abs/2105.03418)  \[[+ poster](https://simdl.github.io/posters/57-supp_DLHMC_Foreman_SimDL-ICLR2021_poster1.pdf)\]  
    [**S. Foreman**, X.Y. Jin, & J.C. Osborn, @ [SimDL Workshop @ ICLR](https://simdl.github.io/), _2021_]{.dim-text}

- [Machine Learning and Neural Networks for Field Theory](https://bit.ly/snowmass_ml2020)  
    [**S. Foreman**, X.Y. Jin, & J.C. Osborn, [SnowMass](https://snowmass21.org/), _2020_]{.dim-text}

- [Examples of renormalization group transformations for image sets](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.98.052129)  
    [**S. Foreman** et al., Physical Review E., _2018_]{.dim-text}

- [RG inspired Machine Learning for lattice field theory](https://arxiv.org/abs/1710.02079)  
    [**S. Foreman** et al., [_arXiv:1710.02079_](https://www.arxiv.or/abs/1710.02079), _2017_]{.dim-text}

- [Large Energy Density in Three-Plate Nanocapacitors due to Coulomb Blockade](https://doi.org/10.1063/1.5009698)  
    [**S. Foreman** et al., _J. Appl. Phys_, _2018_]{.dim-text}

## References

::: {.callout-tip icon=false aria-label="References" title='[📓 References]{.dim-text}' collapse="true" style="text-align: left!important; background-color:rgba(131,131,131,0.05)!important; border: 1px solid rgba(131,131,131,0.0); width: 100%; opacity:100%;"}

- References:
    - [@yan2025mofa]
    - [@gokdemir2025hiperrag]
    - [@dharuman2024mprot]
    - [@parete2024intro]
    - [@cheng2024thorough]
    - [@zvyagin2023genslms]
    - [@dharuman2023protein]
    - [@emani2023comprehensive]
    - [@song2023deepspeed4science]
    - [@foreman2023mlmc]
    - [@boyda2022applications]
    - [@kronfeld2022lattice]
    - [@shanahan2022snowmass]
    - [@2022slft.confE.508F]
    - [@foreman2021hmc]
    - [@foreman2020machine]
    - [@foreman2019learning]
    - [@foreman2018rg]
    - [@hubler2018large]
    - [@foreman2018examples]
    - [@liu2017energy]
    - [@deamont2014superconductivity]


::: {#refs}
:::

:::
