gantt
    title PyTorch Vendor Integration Timeline AMD vs Intel
    dateFormat  YYYY-MM-DD
    axisFormat  %Y

section AMD
    Installable PyTorch ROCm Python packages         :amd2, 2021-03-04,
    ROCm marked stable                               :amd3,2022-06-28,

section PyTorch Releases
    1.8                                             :milestone,crit, pt180, 2021-03-04,
    1.12                                            :pt1120, 2022-06-28,
    2.0                                             :milestone,crit,pt200, 2023-03-15,
    2.4                                             :pt24, 2024-07-24,
    2.5                                             :milestone,crit,pt250, 2024-10-17,
    2.6                                             :pt260, 2025-01-29,
    2.7                                             :pt270, 2025-04-23,
    2.8                                             :crit, pt280, 2025-08-06,
    2.9                                             :pt290, 2025-10-15,
    2.10                                            :pt210, 2026-01-15,

section Intel
    Incremental Intel GPU improvements begin           :int2, 2024-07-24,
    Native Intel GPU support announced in PyTorch 2.5  :int3, 2024-10-17,
    Intel GPU eager and compile parity in PyTorch 2.7  :int4, 2025-04-23,
    Intel XCCL Backend introduced in PyTorch 2.8       :int5, 2025-04-23,
    IPEX discontinued                                  :int6, 2025-08-06, 2026-03-31
    IPEX end of life                                   :int7, 2026-03-31,
