---
editor:
   render-on-save: true
---

#### 📆 2024


::: {.callout-tip icon="false" title="🪧 [[**Parallel Training**](https://saforem2.github.io/parallel-training-slides) @ [AI-4-Science Training Series](https://github.com/argonne-lcf/ai-science-training-series/tree/main/06_parallel_training) \[03/2024\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/parallel-training-slides" title="🪧 Parallel Training Techniques" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip title="🪧 [[**LLMs from Scratch**](https://saforem2.github.io/llm-workshop-talk) @ [LLM Tutorial Workshop](https://github.com/argonne-lcf/llm-workshop) \[02/2024\]]{.dim-text}" icon="false" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-workshop-talk" title="🪧 LLMs from Scratch" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

#### 📆 2023

::: {.callout-tip icon="false" title="🪧 [[**Creating Small(-ish) LLMs**](https://saforem2.github.io/LLM-tutorial) @ [LLM Tutorial Workshop (1)](https://github.com/brettin/llm_tutorial) \[11/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/LLM-tutorial" title="🪧 Creating Small(-ish) LLMs" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Exascale Science on Aurora**](https://samforeman.me/oneapi-talk/index.html#0) @ [Intel oneAPI Workshop @ UIC](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/oneapi-talk" title="🪧 Exascale Science on Aurora" width="100%" align="center" height="500" frameborder="0" style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

<!---->
<!-- ::: {.callout-tip icon="false" title="🪧 [[**LLM Lunch Talk**](https://saforem2.github.io/llm-lunch-talk) @ [ALCF HPC Workshop](https://github.com/argonne-lcf/ALCF_Hands_on_HPC_Workshop)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}: -->
<!---->
<!-- <iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-lunch-talk/#/section" title="🪧 LLMs on Polaris" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> -->
<!--   <p>Your browser does not support iframes.</p> -->
<!-- </iframe> -->
<!---->
<!-- ::: -->

::: {.callout-tip icon="false" title="🪧 [[**LLM Lunch Talk**](https://saforem2.github.io/llm-lunch-talk) @ [ALCF Hands On HPC Workshop](https://www.alcf.anl.gov/events/alcf-hands-hpc-workshop) \[10/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/llm-lunch-talk/#/section" title="🪧 LLMs on Polaris" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Scaling LLMs for Science**](https://saforem2.github.io/scaling4science) @ [Data-Intensive Computing + AI/ML at Scale](https://events.cels.anl.gov/event/426/overview) \[08/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/scaling4science/#/section" title="🪧 Scaling LLMs for Science and Ongoing Collaborations" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**MLMC: Machine Learning Monte Carlo**](https://saforem2.github.io/lattice23) @ [Lattice 2023](https://indico.fnal.gov/event/57249/contributions/271305/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/lattice23/#/title-slide" title="🪧 MLMC: Machine Learning Monte Carlo" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Generative Modeling and Efficient Sampling**](https://saforem2.github.io/lqcd-pasc23/) @ [PASC23](https://pasc23.pasc-conference.org/) \[07/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/lqcd-pasc23/" title="🪧 Generative Modeling and Efficient Sampling" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Efficient Sampling for LGT**](https://saforem2.github.io/deep-fridays) @ [Deep Fridays @ U. Bologna](https://www.cs.unibo.it/~asperti/deep_fridays.html) \[04/2023\]]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/deep-fridays/" title="🪧 Efficient Sampling for LGT" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::


#### 📆 2022


::: {.callout-tip icon="false" title="🪧 [[**Large Scale Training**](https://saforem2.github.io/ai4sci-large-scale-training) @ [AI4Science on Supercomputers (ALCF)](https://github.com/argonne-lcf/ai-science-training-series) (11/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/ai4sci-large-scale-training/#" title="🪧 Large Scale Training" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Hyperparameter Management**](https://saforem2.github.io/hparam-management-sdl2022/) @ [ALCF SDL Workshop](https://www.alcf.anl.gov/events/2022-alcf-simulation-data-and-learning-workshop) (10/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/hparam-management-sdl2022" title="🪧 Hyperparameter Management" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Statistical Learning**](https://saforem2.github.io/ATPESC-StatisticalLearning) @ [ATPESC 2022](https://extremecomputingtraining.anl.gov/) (08/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
- [📕 accompanying notebook](https://github.com/argonne-lcf/ATPESC_MachineLearning/blob/master/00_statisticalLearning/src/atpesc/notebooks/statistical_learning.ipynb)

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/ATPESC-StatisticalLearning/#/" title="🪧 Statistical Learning" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Scientific Data Science: An Emerging Symbiosis**](https://saforem2.github.io/anl-job-talk/) @ ANL (05/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/anl-job-talk" title="🪧 Scientific Data Science" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::

::: {.callout-tip icon="false" title="🪧 [[**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar) @ UNC Greensboro (03/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
- [**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar), at UNC Greensboro, March 2022  

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/physicsSeminar" title="🪧 Machine Learning in HEP" width="100%" align="center" height="300" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border:none;border-radius:0.25rem;"> <p>Your browser does not support iframes.</p> </iframe>
:::


#### 📆 2021


::: {.callout-tip icon="false" title="🪧 [[**Accelerated Sampling Methods for LGT**](https://saforem2.github.io/l2hmc-dwq25/), @ [DWQ @ 25 \[BNL\]](https://indico.bnl.gov/event/13576/) (12/2021)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/l2hmc-dwq25/" title="🪧 Accelerated Sampling Methods for LGT" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::


::: {.callout-tip icon="false" title="🪧 [[**Training Topological Samplers for LGT**](https://saforem2.github.io/l2hmc_talk_ect2021) @ [ML4HEP, ECT\* Trento](https://indico.ectstar.eu/event/77/contributions/2349/) (09/2021)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/l2hmc_talk_ect2021" title="🪧 Training Topological Samplers for LGT" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;"> <p>Your browser does not support iframes.</p> </iframe>
:::


::: {.callout-tip icon="false" title="🪧 [[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) @ MIT Lattice Group Seminar (2021)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:


[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) at the *MIT Lattice Group Seminar*, 2021

:::

<!-- -   [**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) to the [*Machine Learning Techniques in Lattice QCD Workshop*](https://bit.ly/mainz21_overview), 2021 -->

::: {.callout-tip icon="false" title="🪧 [[**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) @ [ML in LQCD Workshop](https://bit.ly/mainz21_overview) (2021)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:
<iframe loading="lazy" allow="picture-in-picture" src="https://bit.ly/mainz21" title="🪧 Deep Learning HMC for Improved Gauge Generation" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
</iframe>

:::

#### 📆 2020

::: {.callout-tip icon="false" title="🪧 [[**Machine Learning for Lattice QCD**](https://slides.com/samforeman/l2hmc-qcd-93bc0c) @ U. Iowa (2020)]{.dim-text}" collapse="true" style="width:100%; background-color: var(--bg-transparent); border-radius:0pt!important;border:none!important;border-left:3px solid rgba(131, 131, 131, 0.33)!important;"}:

<iframe loading="lazy" allow="picture-in-picture" src="https://slides.com/samforeman/l2hmc-qcd-93bc0c" title="🪧 Machine Learning for Lattice QCD" width="100%" align="center" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
</iframe>

:::
