---
title: "Recent Talks"
callout-appearance: simple
title-block-banner: false
# https://www.anl.gov/sites/www/files/2021-09/CPA_RESIZE_Climate%20Resilience%20Images_01_1920x1080.jpg
editor:
   render-on-save: true
execute:
   freeze: true
---

# 

## {{< fa regular calendar >}} 2023

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Scaling LLMs for Science and Ongoing Collaborations**](https://saforem2.github.io/scaling4science) @ [Data-Intensive Computing and AI/ML at Scale](https://events.cels.anl.gov/event/426/overview) (08/2023)]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

<iframe allow="picture-in-picture" src="https://saforem2.github.io/scaling4science/" title="Scaling LLMs for Science and Ongoing Collaborations" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::


::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**MLMC: Machine Learning Monte Carlo**](https://saforem2.github.io/lattice23) @ [Lattice 2023](https://indico.fnal.gov/event/57249/contributions/271305/) (07/2023)]{.dim-text}" collapse="true" style="width:100%; background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

<iframe allow="picture-in-picture" src="https://saforem2.github.io/lattice23/" title="MLMC: Machine Learning Monte Carlo" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Generative Modeling and Efficient Sampling**](https://saforem2.github.io/lqcd-pasc23/) @ [PASC23](https://pasc23.pasc-conference.org/) (07/2023)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

<iframe allow="picture-in-picture" src="https://saforem2.github.io/lqcd-pasc23/" title="Generative Modeling and Efficient Sampling" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Efficient Sampling for Lattice Gauge Theory**](https://saforem2.github.io/deep-fridays) @ [Deep Fridays @ U. Bologna](https://www.cs.unibo.it/~asperti/deep_fridays.html) (04/2023)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

<iframe allow="picture-in-picture" src="https://saforem2.github.io/deep-fridays/" title="Efficient Sampling for Lattice Gauge Theory" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::


## {{< fa regular calendar >}} 2022

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Large Scale Training**](https://saforem2.github.io/ai4sci-large-scale-training) @ [Introduction to AI4Science on Supercomputers (ALCF)](https://github.com/argonne-lcf/ai-science-training-series) (11/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

    
<iframe allow="picture-in-picture" src="https://saforem2.github.io/ai4sci-large-scale-training/#" title="Large Scale Training" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Hyperparameter Management**](https://saforem2.github.io/hparam-management-sdl2022/) @ [ALCF Simulation, Data, and Learning Workshop](https://www.alcf.anl.gov/events/2022-alcf-simulation-data-and-learning-workshop) (10/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

    
<iframe allow="picture-in-picture" src="https://saforem2.github.io/hparam-management-sdl2022" title="Hyperparameter Management" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Statistical Learning**](https://saforem2.github.io/ATPESC-StatisticalLearning) @ [ATPESC 2022](https://extremecomputingtraining.anl.gov/) (08/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- [📕 accompanying notebook](https://github.com/argonne-lcf/ATPESC_MachineLearning/blob/master/00_statisticalLearning/src/atpesc/notebooks/statistical_learning.ipynb)

<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/ATPESC-StatisticalLearning/#/" title="Statistical Learning" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Scientific Data Science: An Emerging Symbiosis**](https://saforem2.github.io/anl-job-talk/) @ ANL (05/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

  
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/anl-job-talk" title="Scientific Data Science" width="100%" align="center" height="512" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border-radius:0.25rem;border:none;align:center;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar) @ UNC Greensboro (03/2022)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- [**Machine Learning in HEP**](https://saforem2.github.io/physicsSeminar), at UNC Greensboro, March 2022
  
<iframe loading="lazy" allow="picture-in-picture" src="https://saforem2.github.io/physicsSeminar" title="Machine Learning in HEP" width="100%" align="center" height="300" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-tip title="Older Slides" collapse="true" style="width:100%;"}
Older slides (pre-2022) can be found [here](../qmd/slides-older.qmd)
:::

