---
title: "(Less) Recent Talks"
callout-appearance: simple
title-block-banner: false
# https://www.anl.gov/sites/www/files/2021-09/CPA_RESIZE_Climate%20Resilience%20Images_01_1920x1080.jpg
editor:
   render-on-save: true
execute:
   freeze: true
---


## {{< fa regular calendar >}} 2021

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Accelerated Sampling Methods for Lattice Gauge Theory**](https://saforem2.github.io/l2hmc-dwq25/), @ [BNL / DWQ @ 25](https://indico.bnl.gov/event/13576/) (12/2021)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

-   
<iframe allow="picture-in-picture" src="https://saforem2.github.io/l2hmc-dwq25" title="Accelerated Sampling Methods for Lattice Gauge Theory" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen width="100%" align="center" height="512" style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [Training Topological Samplers for Lattice Gauge Theory](https://saforem2.github.io/l2hmc_talk_ect2021) @ [ML4HEP, ECT* Trento](https://indico.ectstar.eu/event/77/contributions/2349/) (09/2021)" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

  
<iframe allow="picture-in-picture" src="https://saforem2.github.io/l2hmc_talk_ect2021" title="Training Topological Samplers for Lattice Gauge Theory" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen width="100%" align="center" height="512" style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) @ MIT Lattice Group Seminar (2021)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- [**l2hmc-qcd**](https://github.com/saforem2/l2hmc-qcd) at the _MIT Lattice Group Seminar_, 2021

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) @ [ML in LQCD Workshop](https://bit.ly/mainz21_overview) (2021)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- [**Deep Learning HMC for Improved Gauge Generation**](https://bit.ly/mainz21) to the [_Machine Learning Techniques in Lattice QCD Workshop_](https://bit.ly/mainz21_overview), 2021

:::

## {{< fa regular calendar >}} 2020

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [**Machine Learning for Lattice QCD** (2020)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- [**Machine Learning for Lattice QCD**](https://slides.com/samforeman/l2hmc-qcd-93bc0c) at the University of Iowa, 2020
  
<iframe allow="picture-in-picture" src="https://slides.com/samforeman/l2hmc-qcd/embed" title="Machine Learning for Lattice QCD" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen width="100%" align="center" height="512" style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [[Machine Learning Inspired Analysis of Ising Model](https://bit.ly/latt2018) @ [Lattice](https://indico.fnal.gov/event/15949/overview) (2018)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

<iframe allow="picture-in-picture" src="https://bit.ly/latt2018" title="Machine Learning Inspired Analysis of Ising Model" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen width="100%" align="center" height="512" style="border:none;border-radius:0.25rem;">
    <p>Your browser does not support iframes.</p>
  </iframe>

:::

::: {.callout-caution icon=false title="[{{< fa solid person-chalkboard size=fa-lg >}}]{style='color:#A9A9B3;'} $\hspace{2pt}$ [**Machine Learning Analysis of Ising Worms** (2017)]{.dim-text}" collapse="true" style="width:100%;background-color: rgba(28, 28, 28, 0.75)!important; border-color: #2c2c2c!important;"}

- **Machine Learning Analysis of Ising Worms** at _Brookhaven National Laboratory_, 2017

:::
